name: "Test typescript-action"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          use-policy-store: true
          egress-policy: audit
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run test
      - run: npm run check
      - run: npm run build
